#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           40

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xset +fp /usr/local/share/fonts/
picom --config $HOME/.config/picom/picom.conf &
xrandr --output DP-4 --mode 1920x1080 &
xsetroot -cursor_name left_ptr &
bspc config focus_follows_pointer true &
feh --bg-scale $HOME/.wallpapers/appocalypse.jpg &
polybar example &
